// templates/design-system/src/components/FaqSection.vue
<script setup lang="ts">
import { computed } from 'vue';
import { site } from '../utils/content';

const jsonLd = computed(() =>
  JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: site.faq.items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.answer,
      },
    })),
  }),
);
</script>

<template>
  <section id="faq" class="faq" aria-labelledby="faq-heading">
    <div class="container faq__inner">
      <header class="section-head">
        <p class="kicker">{{ site.faq.kicker }}</p>
        <h2 id="faq-heading">{{ site.faq.heading }}</h2>
      </header>
      <div class="faq__list">
        <details
          v-for="(item, index) in site.faq.items"
          :key="item.question"
          class="faq__item"
          :open="index === 0"
        >
          <summary>
            <span>{{ item.question }}</span>
            <span class="faq__marker" aria-hidden="true"></span>
          </summary>
          <p>{{ item.answer }}</p>
        </details>
      </div>
    </div>
    <component :is="'script'" type="application/ld+json">{{ jsonLd }}</component>
  </section>
</template>

// templates/movement-library/src/components/FaqSection.tsx
import { site } from '../utils/content';

const faqJsonLd = JSON.stringify({
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: site.faqs.map((faq) => ({
    '@type': 'Question',
    name: faq.question,
    acceptedAnswer: {
      '@type': 'Answer',
      text: faq.answer,
    },
  })),
});

export const FaqSection = () => (
  <section className="faq" id="faq" aria-labelledby="faq-heading">
    <div className="container faq-inner">
      <header className="faq-head">
        <h2 id="faq-heading">{site.faqHeading}</h2>
        <p className="faq-intro">{site.faqIntro}</p>
      </header>
      <div className="faq-list">
        {site.faqs.map((faq) => (
          <details key={faq.question} className="faq-item">
            <summary>
              <span>{faq.question}</span>
              <span className="faq-marker" aria-hidden="true" />
            </summary>
            <p className="faq-answer">{faq.answer}</p>
          </details>
        ))}
      </div>
    </div>
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: faqJsonLd }}
    />
  </section>
);
