// templates/design-system/src/components/FaqSection.vue
<script setup lang="ts">
import { computed } from 'vue';
import { site } from '../utils/content';

const jsonLd = computed(() =>
  JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: site.faq.items.map((item) => ({
      '@type': 'Question',
      name: item.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: item.answer,
      },
    })),
  }),
);
</script>

<template>
  <section id="faq" class="faq" aria-labelledby="faq-heading">
    <div class="container faq__inner">
      <header class="section-head">
        <p class="kicker">{{ site.faq.kicker }}</p>
        <h2 id="faq-heading">{{ site.faq.heading }}</h2>
      </header>
      <div class="faq__list">
        <details
          v-for="(item, index) in site.faq.items"
          :key="item.question"
          class="faq__item"
          :open="index === 0"
        >
          <summary>
            <span>{{ item.question }}</span>
            <span class="faq__marker" aria-hidden="true"></span>
          </summary>
          <p>{{ item.answer }}</p>
        </details>
      </div>
    </div>
    <component :is="'script'" type="application/ld+json">{{ jsonLd }}</component>
  </section>
</template>

// templates/drop/src/components/FaqSection.tsx
import { site } from "~/utils/content";

export function FaqSection() {
  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: site.faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };

  return (
    <section className="faq" id="faq" aria-labelledby="faq-title">
      <p className="section-kicker">03 — Questions</p>
      <h2 id="faq-title" className="section-title">
        Asked every drop
      </h2>
      <div className="faq-list">
        {site.faqs.map((faq) => (
          <details className="faq-item" key={faq.question}>
            <summary className="faq-question">
              {faq.question}
              <span className="faq-marker" aria-hidden="true" />
            </summary>
            <p className="faq-answer">{faq.answer}</p>
          </details>
        ))}
      </div>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
    </section>
  );
}
