// templates/engineering-blog/src/components/SiteHeader.tsx
import { Link } from 'gatsby';

import siteData from '../data/site.json';
import { Wordmark } from '../icons/Wordmark';
import type { SiteContent } from '../types/content';

const site = siteData as SiteContent;

export function SiteHeader() {
  return (
    <header className="site-header">
      <div className="site-header__inner">
        <Link className="wordmark" to="/" aria-label={`${site.name} — home`}>
          <Wordmark />
          <span className="wordmark__name">
            {site.wordmark.lead} <em>{site.wordmark.tail}</em>
          </span>
        </Link>
        <nav aria-label="Site">
          <ul className="site-nav">
            {site.nav.map((link) => (
              <li key={link.href}>
                <Link to={link.href}>{link.label}</Link>
              </li>
            ))}
          </ul>
        </nav>
      </div>
    </header>
  );
}

// templates/moving-day/src/components/SiteHeader.vue
<script setup lang="ts">
import site from '../data/site.json';
</script>

<template>
  <header class="site-header">
    <a
      class="brand"
      href="#"
      :aria-label="`${site.name} home`"
    >
      <span
        class="brand-mark"
        aria-hidden="true"
      ><i /><i /><i /></span>
      <span>{{ site.name }}</span>
    </a>
    <nav aria-label="Main navigation">
      <a href="#estimate">Get an estimate</a>
      <a href="#how-it-works">How it works</a>
      <a href="#faq">FAQs</a>
    </nav>
    <a
      class="phone-link"
      :href="site.phoneHref"
    >
      <span aria-hidden="true">↗</span>
      {{ site.phoneDisplay }}
    </a>
  </header>
</template>
